
package mx.profuturo.nci.ws.webservice.indicadores.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import mx.profuturo.nci.ws.webservice.catalogo.impl.ICatalogoSoapWSService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IIndicadoresSoapWSService", targetNamespace = "http://impl.indicadores.webservice.ws.nci.profuturo.mx/", wsdlLocation = "http://172.16.60.67:9083/mit-ws/services/IIndicadoresSoapWSService?wsdl")
public class IIndicadoresSoapWSService
    extends Service
{

    private final static URL IINDICADORESSOAPWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.profuturo.nci.ws.webservice.indicadores.impl.IIndicadoresSoapWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.profuturo.nci.ws.webservice.indicadores.impl.IIndicadoresSoapWSService.class.getResource(".");
            url = //new URL(baseUrl, "http://172.16.60.67:9083/mit-ws/services/IIndicadoresSoapWSService?wsdl");
            		IIndicadoresSoapWSService.class.getClassLoader().getResource("config/wsdls/indicadores/IIndicadoresSoapWSService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.60.67:9083/mit-ws/services/IIndicadoresSoapWSService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IINDICADORESSOAPWSSERVICE_WSDL_LOCATION = url;
    }

    public IIndicadoresSoapWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IIndicadoresSoapWSService() {
        super(IINDICADORESSOAPWSSERVICE_WSDL_LOCATION, new QName("http://impl.indicadores.webservice.ws.nci.profuturo.mx/", "IIndicadoresSoapWSService"));
    }

    /**
     * 
     * @return
     *     returns IIndicadoresSoapWS
     */
    @WebEndpoint(name = "IIndicadoresSoapWSPort")
    public IIndicadoresSoapWS getIIndicadoresSoapWSPort() {
        return super.getPort(new QName("http://impl.indicadores.webservice.ws.nci.profuturo.mx/", "IIndicadoresSoapWSPort"), IIndicadoresSoapWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IIndicadoresSoapWS
     */
    @WebEndpoint(name = "IIndicadoresSoapWSPort")
    public IIndicadoresSoapWS getIIndicadoresSoapWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.indicadores.webservice.ws.nci.profuturo.mx/", "IIndicadoresSoapWSPort"), IIndicadoresSoapWS.class, features);
    }

}
