
package profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DomiciliacionService", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1", wsdlLocation = "http://172.16.60.69:7801/iib/apovol/Domiciliaciones/DomiciliacionService/v1?wsdl")
public class DomiciliacionService
    extends Service
{

    private final static URL DOMICILIACIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.DomiciliacionService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.DomiciliacionService.class.getResource(".");
            url = //new URL(baseUrl, "http://172.16.60.69:7801/iib/apovol/Domiciliaciones/DomiciliacionService/v1?wsdl");
            		DomiciliacionService.class.getClassLoader().getResource("config/wsdls/domiciliacion/DomiciliacionService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'config/wsdls/domiciliacion/DomiciliacionService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOMICILIACIONSERVICE_WSDL_LOCATION = url;
    }

    public DomiciliacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DomiciliacionService() {
        super(DOMICILIACIONSERVICE_WSDL_LOCATION, new QName("http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1", "DomiciliacionService"));
    }

    /**
     * 
     * @return
     *     returns DomiciliacionPortType
     */
    @WebEndpoint(name = "DomiciliacionPort")
    public DomiciliacionPortType getDomiciliacionPort() {
        return super.getPort(new QName("http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1", "DomiciliacionPort"), DomiciliacionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DomiciliacionPortType
     */
    @WebEndpoint(name = "DomiciliacionPort")
    public DomiciliacionPortType getDomiciliacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1", "DomiciliacionPort"), DomiciliacionPortType.class, features);
    }

}
