
package profuturo.mx.iib.apovol.filenet.filenetservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import profuturo.mx.iib.apovol.filenet.filenetservice.v1.types.SubirArchivosReq;
import profuturo.mx.iib.apovol.filenet.filenetservice.v1.types.SubirArchivosResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FileNetPortType", targetNamespace = "http://mx.profuturo/iib/apovol/FileNet/FileNetService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    profuturo.mx.iib.iibexception.iibexception.ObjectFactory.class,
    profuturo.mx.nci.modelo.ObjectFactory.class,
    profuturo.mx.iib.apovol.filenet.filenetservice.v1.types.ObjectFactory.class
})
public interface FileNetPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.filenet.filenetservice.v1.types.SubirArchivosResp
     */
    @WebMethod(action = "urn:subirArchivos")
    @WebResult(name = "subirArchivosResponse", targetNamespace = "http://mx.profuturo/iib/apovol/FileNet/FileNetService/v1/types", partName = "parameters")
    public SubirArchivosResp subirArchivos(
        @WebParam(name = "subirArchivosRequest", targetNamespace = "http://mx.profuturo/iib/apovol/FileNet/FileNetService/v1/types", partName = "parameters")
        SubirArchivosReq parameters);

}
