
package mx.com.profuturo_gnp.ws.sso.controlacceso;

import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ControlAccesoSSOService", targetNamespace = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", wsdlLocation = "http://172.16.50.251:8020/intranet/ws/ControlAccesoSSOService?wsdl")
public class ControlAccesoSSOService
    extends Service
{

    private final static URL CONTROLACCESOSSOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.com.profuturo_gnp.ws.sso.controlacceso.ControlAccesoSSOService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.com.profuturo_gnp.ws.sso.controlacceso.ControlAccesoSSOService.class.getResource(".");
            url = //new URL(baseUrl, "http://172.16.50.251:8020/intranet/ws/ControlAccesoSSOService?wsdl");
            		ControlAccesoSSOService.class.getClassLoader().getResource("config/wsdls/usuario/ControlAccesoSSOService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.50.251:8020/intranet/ws/ControlAccesoSSOService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONTROLACCESOSSOSERVICE_WSDL_LOCATION = url;
    }

    public ControlAccesoSSOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControlAccesoSSOService() {
        super(CONTROLACCESOSSOSERVICE_WSDL_LOCATION, new QName("http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", "ControlAccesoSSOService"));
    }

    /**
     * 
     * @return
     *     returns ControlAccesoSSOPortType
     */
    @WebEndpoint(name = "ControlAccesoSSOPortType")
    public ControlAccesoSSOPortType getControlAccesoSSOPortType() {
        return super.getPort(new QName("http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", "ControlAccesoSSOPortType"), ControlAccesoSSOPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControlAccesoSSOPortType
     */
    @WebEndpoint(name = "ControlAccesoSSOPortType")
    public ControlAccesoSSOPortType getControlAccesoSSOPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", "ControlAccesoSSOPortType"), ControlAccesoSSOPortType.class, features);
    }

}
