
package profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClienteService", targetNamespace = "http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1", wsdlLocation = "http://172.16.60.69:7800/iib/nci/IdentificacionCliente/ClienteService/v1?wsdl")
public class ClienteService
    extends Service
{

    private final static URL CLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTESERVICE_EXCEPTION;
    private final static QName CLIENTESERVICE_QNAME = new QName("http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1", "ClienteService");
    private final static Logger logger = Logger.getLogger(profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.ClienteService.class.getName());

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = //new URL("http://172.16.60.69:7800/iib/nci/IdentificacionCliente/ClienteService/v1?wsdl");
            		ClienteService.class.getClassLoader().getResource("config/wsdls/cliente/ClienteService.wsdl");
        }  catch (Exception ex) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.60.69:7800/iib/nci/IdentificacionCliente/ClienteService/v1?wsdl', retrying as a local file");
            logger.warning(ex.getMessage());
        }
        CLIENTESERVICE_WSDL_LOCATION = url;
        CLIENTESERVICE_EXCEPTION = e;
    }

    public ClienteService() {
        super(__getWsdlLocation(), CLIENTESERVICE_QNAME);
    }

//    public ClienteService(WebServiceFeature... features) {
//        super(__getWsdlLocation(), CLIENTESERVICE_QNAME, features);
//    }

    public ClienteService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTESERVICE_QNAME);
    }

//    public ClienteService(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, CLIENTESERVICE_QNAME, features);
//    }

    public ClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

//    public ClienteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns ClientePortType
     */
    @WebEndpoint(name = "ClientePort")
    public ClientePortType getClientePort() {
        return super.getPort(new QName("http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1", "ClientePort"), ClientePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientePortType
     */
    @WebEndpoint(name = "ClientePort")
    public ClientePortType getClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1", "ClientePort"), ClientePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTESERVICE_EXCEPTION!= null) {
            throw CLIENTESERVICE_EXCEPTION;
        }
        return CLIENTESERVICE_WSDL_LOCATION;
    }

}
