
package mx.profuturo.nci.ws.webservice.catalogo.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.profuturo.nci.ws.webservice.catalogo.CatalogoConsultarBeanRequest;
import mx.profuturo.nci.ws.webservice.catalogo.CatalogoConsultarPorRolesBeanRequest;
import mx.profuturo.nci.ws.webservice.catalogo.ICatalogoSoapWSConsultarPorRolesResponse;
import mx.profuturo.nci.ws.webservice.catalogo.ICatalogoSoapWSConsultarResponse;
import mx.profuturo.nci.ws.webservice.catalogo.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICatalogoSoapWS", targetNamespace = "http://catalogo.webservice.ws.nci.profuturo.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICatalogoSoapWS {


    /**
     * 
     * @param request
     * @return
     *     returns mx.profuturo.nci.ws.webservice.catalogo.ICatalogoSoapWSConsultarResponse
     */
    @WebMethod
    @WebResult(name = "ConsultarResponse", targetNamespace = "")
    @RequestWrapper(localName = "consultar", targetNamespace = "http://catalogo.webservice.ws.nci.profuturo.mx/", className = "mx.profuturo.nci.ws.webservice.catalogo.Consultar")
    @ResponseWrapper(localName = "consultarResponse", targetNamespace = "http://catalogo.webservice.ws.nci.profuturo.mx/", className = "mx.profuturo.nci.ws.webservice.catalogo.ConsultarResponse")
    public ICatalogoSoapWSConsultarResponse consultar(
        @WebParam(name = "request", targetNamespace = "")
        CatalogoConsultarBeanRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mx.profuturo.nci.ws.webservice.catalogo.ICatalogoSoapWSConsultarPorRolesResponse
     */
    @WebMethod
    @WebResult(name = "ConsultarPorRolesResponse", targetNamespace = "")
    @RequestWrapper(localName = "consultarPorRoles", targetNamespace = "http://catalogo.webservice.ws.nci.profuturo.mx/", className = "mx.profuturo.nci.ws.webservice.catalogo.ConsultarPorRoles")
    @ResponseWrapper(localName = "consultarPorRolesResponse", targetNamespace = "http://catalogo.webservice.ws.nci.profuturo.mx/", className = "mx.profuturo.nci.ws.webservice.catalogo.ConsultarPorRolesResponse")
    public ICatalogoSoapWSConsultarPorRolesResponse consultarPorRoles(
        @WebParam(name = "request", targetNamespace = "")
        CatalogoConsultarPorRolesBeanRequest request);

}
