
package profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarListaTraspasoReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarPreSolicitudReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarPreSolicitudResp;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarSolicitudReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarSolicitudResp;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarTraspasoReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarTraspasoResp;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarPagoTraspasoReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarPagoTraspasoResp;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarPreSolicitudReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarPreSolicitudResp;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarSolicitudReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarSolicitudResp;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.GuardarPreSolicitudReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.GuardarSolicitudResp;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.RechazarPendientesPorFolioReq;
import profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.RechazarPendientesPorFolioResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DomiciliacionPortType", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    profuturo.mx.iib.iibexception.iibexception.ObjectFactory.class,
    profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ObjectFactory.class,
    profuturo.mx.nci.modelo.ObjectFactory.class
})
public interface DomiciliacionPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarPreSolicitudResp
     */
    @WebMethod(action = "urn:consultarPreSolicitud")
    @WebResult(name = "consultarPreSolicitudResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
    public ConsultarPreSolicitudResp consultarPreSolicitud(
        @WebParam(name = "consultarPreSolicitudRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        ConsultarPreSolicitudReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarPreSolicitudResp
     */
    @WebMethod(action = "urn:actualizarPreSolicitud")
    @WebResult(name = "actualizarPreSolicitudResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
    public ActualizarPreSolicitudResp actualizarPreSolicitud(
        @WebParam(name = "actualizarPreSolicitudRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        ActualizarPreSolicitudReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.RechazarPendientesPorFolioResp
     */
    @WebMethod(action = "urn:rechazarPendientesPorFolio")
    @WebResult(name = "rechazarPendientesPorFolioResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
    public RechazarPendientesPorFolioResp rechazarPendientesPorFolio(
        @WebParam(name = "rechazarPendientesPorFolioRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        RechazarPendientesPorFolioReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.GuardarSolicitudResp
     */
    @WebMethod(action = "urn:guardarSolicitud")
    @WebResult(name = "guardarSolicitudResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
    public GuardarSolicitudResp guardarSolicitud(
        @WebParam(name = "guardarSolicitudRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        GuardarPreSolicitudReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarSolicitudResp
     */
    @WebMethod(action = "urn:consultarSolicitud")
    @WebResult(name = "consultarSolicitudResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
    public ConsultarSolicitudResp consultarSolicitud(
        @WebParam(name = "consultarSolicitudRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        ConsultarSolicitudReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarSolicitudResp
     */
    @WebMethod(action = "urn:actualizarSolicitud")
    @WebResult(name = "actualizarSolicitudResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
    public ActualizarSolicitudResp actualizarSolicitud(
        @WebParam(name = "actualizarSolicitudRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        ActualizarSolicitudReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ActualizarTraspasoResp
     */
    @WebMethod(action = "urn:actualizarTraspaso")
    @WebResult(name = "actualizarTraspasoResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
    public ActualizarTraspasoResp actualizarTraspaso(
        @WebParam(name = "actualizarTraspasoRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        ActualizarTraspasoReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.domiciliaciones.domiciliacionservice.v1.types.ConsultarPagoTraspasoResp
     */
    @WebMethod(action = "consultarPagoTraspaso")
    @WebResult(name = "consultarPagoTraspasoResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
    public ConsultarPagoTraspasoResp consultarPagoTraspaso(
        @WebParam(name = "consultarPagoTraspasoRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        ConsultarPagoTraspasoReq parameters);

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "actualizarListaTraspaso")
    @Oneway
    public void actualizarListaTraspaso(
        @WebParam(name = "actualizarListaTraspasoRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Domiciliaciones/DomiciliacionService/v1/types", partName = "parameters")
        ActualizarListaTraspasoReq parameters);

}
