
package profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MatrizConvivenciaService", targetNamespace = "http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1", wsdlLocation = "file:/opt/IDE/workspace.fase2/mit-ws-client/src/main/resources/config/wsdls/matrizConvivencia/MatrizConvivenciaService.wsdl")
public class MatrizConvivenciaService
    extends Service
{

    private final static URL MATRIZCONVIVENCIASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.MatrizConvivenciaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.MatrizConvivenciaService.class.getResource(".");
            url = //new URL(baseUrl, "/src/main/resources/config/wsdls/matrizConvivencia/MatrizConvivenciaService.wsdl");
            		MatrizConvivenciaService.class.getClassLoader().getResource("config/wsdls/matrizConvivencia/MatrizConvivenciaService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: '/src/main/resources/config/wsdls/matrizConvivencia/MatrizConvivenciaService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MATRIZCONVIVENCIASERVICE_WSDL_LOCATION = url;
    }

    public MatrizConvivenciaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MatrizConvivenciaService() {
        super(MATRIZCONVIVENCIASERVICE_WSDL_LOCATION, new QName("http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1", "MatrizConvivenciaService"));
    }

    /**
     * 
     * @return
     *     returns MatrizConvivenciaPortType
     */
    @WebEndpoint(name = "MatrizConvivenciaPort")
    public MatrizConvivenciaPortType getMatrizConvivenciaPort() {
        return super.getPort(new QName("http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1", "MatrizConvivenciaPort"), MatrizConvivenciaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MatrizConvivenciaPortType
     */
    @WebEndpoint(name = "MatrizConvivenciaPort")
    public MatrizConvivenciaPortType getMatrizConvivenciaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1", "MatrizConvivenciaPort"), MatrizConvivenciaPortType.class, features);
    }

}
