package mx.profuturo.nci.business.util;

public enum WebSphereNamespace 
{
	WS_ENDPOINT_CLIENT_SOAP_FOLIO("WS.SOAP.ENDPOINT.CLIENT.FOLIO"),//http://172.16.50.251:8020/intranet/ws/ControlAccesoSSOService
	WS_ENDPOINT_CLIENT_SOAP_CUENTA_CERTIFICADA("WS.SOAP.ENDPOINT.CLIENT.CUENTA.CERTIFICADA"),//http://172.16.50.251:8020/intranet/ws/ControlAccesoSSOService
	WS_ENDPOINT_CLIENT_SOAP_AUTH("WS.SOAP.ENDPOINT.CLIENT.AUTH.SSO"),//http://172.16.50.251:8020/intranet/ws/ControlAccesoSSOService
	ws_endpoint_client_notificaciones("WS.SOAP.ENDPOINT.CLIENT.NOTIFICACIONES"),//http://172.16.50.251:8020/intranet/ws/ControlAccesoSSOService
	WS_ENDPOINT_CLIENT_SOAP_CONSULTA_CLIENTE("WS.SOAP.ENDPOINT.CLIENT.CLIENTE"),//http://172.16.60.69:7800/iib/nci/IdentificacionCliente/ClienteService/v1
	WS_ENDPOINT_CLIENT_SOAP_CATALOGO_COMUN("WS.SOAP.ENDPOINT.CLIENT.CATALOGO.COMUN"),//http://172.16.50.231:8010/MitAforeComunWEB/CatalogoComunService
	WS_ENDPOINT_CLIENT_SOAP_OPERACIONES_LDAP("WS.SOAP.ENDPOINT.CLIENT.OPERACIONES.LDAP"),//http://172.16.38.19:9081/LdapServiceWEB/OperacionesLdapService
	WS_ENDPOINT_CLIENT_SOAP_NCI_CATALOGO("WS_ENDPOINT_CLIENT_SOAP_NCI_CATALOGO"),
	WS_ENDPOINT_CLIENT_SOAP_FILENET("WS_ENDPOINT_CLIENT_SOAP_FILENET"),
	WS_ENDPOINT_CLIENT_SOAP_INDICADORES("WS_ENDPOINT_CLIENT_SOAP_INDICADORES"),
	WS_ENDPOINT_CLIENT_SOAP_MATRIZ("WS.ENDPOINT.CLIENT.SOAP.MATRIZ"),//http://172.16.60.69:7802/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1
	WS_ENDPOINT_CLIENT_SOAP_CONCILIACION("WS.ENDPOINT.CLIENT.SOAP.CONCILIACION"),
	WS_ENDPOINT_CLIENT_SOAP_DOMICILIACION("WS.ENDPOINT.CLIENT.SOAP.DOMICILIACION"),
    WS_ENDPOINT_CLIENT_SOAP_DICTAMEN_RECHAZADA("WS.ENDPOINT.CLIENT.SOAP.DICTAMEN_RECHAZADA"), //http://172.16.60.70:7806/iib/recaudacion/reclasificacionApoVol/ValidarTramite/AP_ResultadoDictamenRechazada/v1?wsdl
	MIT_NCI_AV_GEN_ARCHIVO_DOMI_BANCOMER_PATH("mit.nci.av.gen.archivo.domi.bancomer.path"),
	MIT_NCI_AV_GEN_ARCHIVO_DOMI_BANAMEX_PATH("mit.nci.av.gen.archivo.domi.banamex.path"),
	MIT_NCI_AV_PROFUTURO_REPOSITORIO_TESORERIA_DOMAIN("mit.nci.profuturo.repositorio.tesoreria.domain"),
	MIT_NCI_AV_PROFUTURO_REPOSITORIO_TESORERIA_USERNAME("mit.nci.profuturo.repositorio.tesoreria.username"),
	MIT_NCI_AV_PROFUTURO_REPOSITORIO_TESORERIA_PASSWORD("mit.nci.profuturo.repositorio.tesoreria.password"),
	MIT_NCI_AV_PROFUTURO_PAGO_APOVOL_ID_PREFIX("mit.nci.profuturo.pago.apovol.id.prefix"),
	MIT_NCI_AV_WEB_ID_APP_AUTH_NAME("mit.nci.av.web.id.app.auth.name"),
	WS_ENDPOINT_CLIENT_SOAP_F4_MANTENIMIENTO_JAV_LIBERACION_DOMI("WS.ENDPOINT.CLIENT.SOAP.F4.MANTENIMIENTO.JAV.LIBERACION.DOMI"),
	WS_ENDPOINT_CLIENT_SOAP_F4_MANTENIMIENTO_JAV_CATALOGO_CONTRATO("WS.ENDPOINT.CLIENT.SOAP.F4.MANTENIMIENTO.JAV.CATALOGO.CONTRATO"),
	WS_ENDPOINT_CLIENT_SOAP_F4_MANTENIMIENTO_BUS_DOMIS("WS.ENDPOINT.CLIENT.SOAP.F4.MANTENIMIENTO.BUS.DOMIS")
	;
	
	private String value;
	
	WebSphereNamespace(String value)
	{
		this.value=value;
	}
	
	public String getValue()
	{
		return this.value;
	}
	
	
}
