
package mx.profuturo.ldap.operacionesldap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OperacionesLdapService", targetNamespace = "http://www.profuturo.mx/ldap/OperacionesLdap", wsdlLocation = "http://172.16.38.19:9081/LdapServiceWEB/wsdl/OperacionesLdapService.wsdl")
public class OperacionesLdapService
    extends Service
{

    private final static URL OPERACIONESLDAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.profuturo.ldap.operacionesldap.OperacionesLdapService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.profuturo.ldap.operacionesldap.OperacionesLdapService.class.getResource(".");
            url = //new URL(baseUrl, "http://172.16.38.19:9081/LdapServiceWEB/wsdl/OperacionesLdapService.wsdl");
            			OperacionesLdapService.class.getClassLoader().getResource("config/wsdls/usuario/OperacionesLdapService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.38.19:9081/LdapServiceWEB/wsdl/OperacionesLdapService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OPERACIONESLDAPSERVICE_WSDL_LOCATION = url;
    }

    public OperacionesLdapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperacionesLdapService() {
        super(OPERACIONESLDAPSERVICE_WSDL_LOCATION, new QName("http://www.profuturo.mx/ldap/OperacionesLdap", "OperacionesLdapService"));
    }

    /**
     * 
     * @return
     *     returns OperacionesLdapServices
     */
    @WebEndpoint(name = "OperacionesLdapPort")
    public OperacionesLdapServices getOperacionesLdapPort() {
        return super.getPort(new QName("http://www.profuturo.mx/ldap/OperacionesLdap", "OperacionesLdapPort"), OperacionesLdapServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OperacionesLdapServices
     */
    @WebEndpoint(name = "OperacionesLdapPort")
    public OperacionesLdapServices getOperacionesLdapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.profuturo.mx/ldap/OperacionesLdap", "OperacionesLdapPort"), OperacionesLdapServices.class, features);
    }

}
