
package profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CuentasCertificadasService", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1", wsdlLocation = "file:/C:/Users/eromerod/Documents/Profuturo/NCI_MONITOR/mit-ws-client/src/main/resources/wsdls/cuentaCertificada/CuentasCertificadasService.wsdl")
public class CuentasCertificadasService
    extends Service
{

    private final static URL CUENTASCERTIFICADASSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.CuentasCertificadasService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.CuentasCertificadasService.class.getResource(".");
            url = //new URL(baseUrl, "file:/C:/Users/eromerod/Documents/Profuturo/NCI_MONITOR/mit-ws-client/src/main/resources/wsdls/cuentaCertificada/CuentasCertificadasService.wsdl");
            CuentasCertificadasService.class.getClassLoader().getResource("config/wsdls/cuentaCertificada/CuentasCertificadasService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/eromerod/Documents/Profuturo/NCI_MONITOR/mit-ws-client/src/main/resources/wsdls/cuentaCertificada/CuentasCertificadasService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CUENTASCERTIFICADASSERVICE_WSDL_LOCATION = url;
    }

    public CuentasCertificadasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CuentasCertificadasService() {
        super(CUENTASCERTIFICADASSERVICE_WSDL_LOCATION, new QName("http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1", "CuentasCertificadasService"));
    }

    /**
     * 
     * @return
     *     returns CuentasCertificadasPortType
     */
    @WebEndpoint(name = "CuentasCertificadasPort")
    public CuentasCertificadasPortType getCuentasCertificadasPort() {
        return super.getPort(new QName("http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1", "CuentasCertificadasPort"), CuentasCertificadasPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CuentasCertificadasPortType
     */
    @WebEndpoint(name = "CuentasCertificadasPort")
    public CuentasCertificadasPortType getCuentasCertificadasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1", "CuentasCertificadasPort"), CuentasCertificadasPortType.class, features);
    }

}
