
package profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1;

import javax.xml.ws.WebFault;
import profuturo.mx.iib.iibexception.iibexception.IIBException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "iibException", targetNamespace = "http://mx.profuturo/iib/iibException/IIBException")
public class FaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IIBException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FaultMsg(String message, IIBException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FaultMsg(String message, IIBException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: profuturo.mx.iib.iibexception.iibexception.IIBException
     */
    public IIBException getFaultInfo() {
        return faultInfo;
    }

}
