
package mx.com.profuturo_gnp.comun.catalogo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CatalogoComun", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo")
@XmlSeeAlso({
    mx.com.profuturo_gnp.web.exception.ObjectFactory.class,
    mx.com.profuturo_gnp.comun.catalogo.ObjectFactory.class
})
public interface CatalogoComun {


    /**
     * 
     * @param relTipoDocumentoIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.RelTipoDocumentoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "relTipoDocumentoOut", targetNamespace = "")
    @RequestWrapper(localName = "consultaCatalogoDocumentoSoporte", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaCatalogoDocumentoSoporte")
    @ResponseWrapper(localName = "consultaCatalogoDocumentoSoporteResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaCatalogoDocumentoSoporteResponse")
    public RelTipoDocumentoOut consultaCatalogoDocumentoSoporte(
        @WebParam(name = "relTipoDocumentoIn", targetNamespace = "")
        RelTipoDocumentoIn relTipoDocumentoIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarCatalogoModificacionEstatusIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarCatalogoModificacionEstatusOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "ConsultarCatalogoModificacionEstatusOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarCatalogoModificacionEstatus", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarCatalogoModificacionEstatus")
    @ResponseWrapper(localName = "consultarCatalogoModificacionEstatusResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarCatalogoModificacionEstatusResponse")
    public ConsultarCatalogoModificacionEstatusOut consultarCatalogoModificacionEstatus(
        @WebParam(name = "ConsultarCatalogoModificacionEstatusIn", targetNamespace = "")
        ConsultarCatalogoModificacionEstatusIn consultarCatalogoModificacionEstatusIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarInformacionEntidadFederativaIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarInformacionEntidadFederativaOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarInformacionEntidadFederativaOut", targetNamespace = "")
    @RequestWrapper(localName = "consultaInformacionEntidadFederativa", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaInformacionEntidadFederativa")
    @ResponseWrapper(localName = "consultaInformacionEntidadFederativaResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaInformacionEntidadFederativaResponse")
    public ConsultarInformacionEntidadFederativaOut consultaInformacionEntidadFederativa(
        @WebParam(name = "consultarInformacionEntidadFederativaIn", targetNamespace = "")
        ConsultarInformacionEntidadFederativaIn consultarInformacionEntidadFederativaIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarEntidadFederativaPorClaveImssIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarInformacionEntidadFederativaOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarInformacionEntidadFederativaOut", targetNamespace = "")
    @RequestWrapper(localName = "consultaEntidadFederativaPorClaveImss", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaEntidadFederativaPorClaveImss")
    @ResponseWrapper(localName = "consultaEntidadFederativaPorClaveImssResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaEntidadFederativaPorClaveImssResponse")
    public ConsultarInformacionEntidadFederativaOut consultaEntidadFederativaPorClaveImss(
        @WebParam(name = "consultarEntidadFederativaPorClaveImssIn", targetNamespace = "")
        ConsultarEntidadFederativaPorClaveImssIn consultarEntidadFederativaPorClaveImssIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultaEntidadFederativaPorClaveRenapoIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultaEntidadFederativaPorClaveRenapoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultaEntidadFederativaPorClaveRenapoOut", targetNamespace = "")
    @RequestWrapper(localName = "consultaEntidadFederativaPorClaveRenapo", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaEntidadFederativaPorClaveRenapo")
    @ResponseWrapper(localName = "consultaEntidadFederativaPorClaveRenapoResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaEntidadFederativaPorClaveRenapoResponse")
    public ConsultaEntidadFederativaPorClaveRenapoOut consultaEntidadFederativaPorClaveRenapo(
        @WebParam(name = "consultaEntidadFederativaPorClaveRenapoIn", targetNamespace = "")
        ConsultaEntidadFederativaPorClaveRenapoIn consultaEntidadFederativaPorClaveRenapoIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarPromotorPorIdEmpleado
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarPromotorOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarPromotorOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarPromotorPorIdEmpleado", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarPromotorPorIdEmpleado")
    @ResponseWrapper(localName = "consultarPromotorPorIdEmpleadoResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarPromotorPorIdEmpleadoResponse")
    public ConsultarPromotorOut consultarPromotorPorIdEmpleado(
        @WebParam(name = "consultarPromotorPorIdEmpleado", targetNamespace = "")
        ConsultarPromotorPorIdEmpleadoIn consultarPromotorPorIdEmpleado)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarEmpleadoIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarEmpleadoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarEmpleadoOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarEmpleado", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarEmpleado")
    @ResponseWrapper(localName = "consultarEmpleadoResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarEmpleadoResponse")
    public ConsultarEmpleadoOut consultarEmpleado(
        @WebParam(name = "consultarEmpleadoIn", targetNamespace = "")
        ConsultarEmpleadoIn consultarEmpleadoIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarCatalogoIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarCatalogoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarCatalogoOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarCatalogo", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarCatalogo")
    @ResponseWrapper(localName = "consultarCatalogoResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarCatalogoResponse")
    public ConsultarCatalogoOut consultarCatalogo(
        @WebParam(name = "consultarCatalogoIn", targetNamespace = "")
        ConsultarCatalogoIn consultarCatalogoIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarInformacionElementoIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarInformacionElementoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarInformacionElementoOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarInformacionElemento", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarInformacionElemento")
    @ResponseWrapper(localName = "consultarInformacionElementoResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarInformacionElementoResponse")
    public ConsultarInformacionElementoOut consultarInformacionElemento(
        @WebParam(name = "consultarInformacionElementoIn", targetNamespace = "")
        ConsultarInformacionElementoIn consultarInformacionElementoIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarGruposIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarCatalogoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarGruposPorFamiliaOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarGrupos", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarGrupos")
    @ResponseWrapper(localName = "consultarGruposResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarGruposResponse")
    public ConsultarCatalogoOut consultarGrupos(
        @WebParam(name = "consultarGruposIn", targetNamespace = "")
        ConsultarGruposIn consultarGruposIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarFamGrpoIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarFamGrpoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarFamGrpoPorSubcuentaOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarFamGrpoPorSubcuenta", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarFamGrpoPorSubcuenta")
    @ResponseWrapper(localName = "consultarFamGrpoPorSubcuentaResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarFamGrpoPorSubcuentaResponse")
    public ConsultarFamGrpoOut consultarFamGrpoPorSubcuenta(
        @WebParam(name = "consultarFamGrpoIn", targetNamespace = "")
        ConsultarFamGrpoIn consultarFamGrpoIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarSubcuentasIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentasOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarSubcuentasOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarSubcuentas", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentas")
    @ResponseWrapper(localName = "consultarSubcuentasResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentasResponse")
    public ConsultarSubcuentasOut consultarSubcuentas(
        @WebParam(name = "consultarSubcuentasIn", targetNamespace = "")
        ConsultarSubcuentasIn consultarSubcuentasIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarPreciosAccionIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarPreciosAccionAivOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarPreciosAccionAivOut", targetNamespace = "")
    @RequestWrapper(localName = "consultaPreciosAIV", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaPreciosAIV")
    @ResponseWrapper(localName = "consultaPreciosAIVResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaPreciosAIVResponse")
    public ConsultarPreciosAccionAivOut consultaPreciosAIV(
        @WebParam(name = "consultarPreciosAccionIn", targetNamespace = "")
        ConsultarPreciosAccionIn consultarPreciosAccionIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarPreciosAccionIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarPreciosAccionOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarPreciosAccionOut", targetNamespace = "")
    @RequestWrapper(localName = "consultaPreciosAccion", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaPreciosAccion")
    @ResponseWrapper(localName = "consultaPreciosAccionResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaPreciosAccionResponse")
    public ConsultarPreciosAccionOut consultaPreciosAccion(
        @WebParam(name = "consultarPreciosAccionIn", targetNamespace = "")
        ConsultarPreciosAccionIn consultarPreciosAccionIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarSubcuentaIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentasOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarSubcuentasPorFamGpo", targetNamespace = "")
    @RequestWrapper(localName = "consultarSubcuentasPorFamGpo", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentasPorFamGpo")
    @ResponseWrapper(localName = "consultarSubcuentasPorFamGpoResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentasPorFamGpoResponse")
    public ConsultarSubcuentasOut consultarSubcuentasPorFamGpo(
        @WebParam(name = "consultarSubcuentaIn", targetNamespace = "")
        ConsultarSubcuentaIn consultarSubcuentaIn)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.MotivosRechazoSolMDOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "motivosRechazoSolMDOut", targetNamespace = "")
    @RequestWrapper(localName = "consultaMotivosRechazoSolMd", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaMotivosRechazoSolMd")
    @ResponseWrapper(localName = "consultaMotivosRechazoSolMdResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultaMotivosRechazoSolMdResponse")
    public MotivosRechazoSolMDOut consultaMotivosRechazoSolMd()
        throws ServiceException
    ;

    /**
     * 
     * @param consultarElementoIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarElementoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarElementoOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarElemento", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarElemento")
    @ResponseWrapper(localName = "consultarElementoResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarElementoResponse")
    public ConsultarElementoOut consultarElemento(
        @WebParam(name = "consultarElementoIn", targetNamespace = "")
        ConsultarElementoIn consultarElementoIn)
        throws ServiceException
    ;

    /**
     * 
     * @param buscarMunicipioPorEntidadIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.BuscarMunicipioPorEntidadOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "buscarMunicipioPorEntidadOut", targetNamespace = "")
    @RequestWrapper(localName = "buscarMunicipioPorEntidad", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.BuscarMunicipioPorEntidad")
    @ResponseWrapper(localName = "buscarMunicipioPorEntidadResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.BuscarMunicipioPorEntidadResponse")
    public BuscarMunicipioPorEntidadOut buscarMunicipioPorEntidad(
        @WebParam(name = "buscarMunicipioPorEntidadIn", targetNamespace = "")
        BuscarMunicipioPorEntidadIn buscarMunicipioPorEntidadIn)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.BuscarEntidadesFederativasOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "buscarEntidadesFederativasOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarEntidadesFederativas", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarEntidadesFederativas")
    @ResponseWrapper(localName = "consultarEntidadesFederativasResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarEntidadesFederativasResponse")
    public BuscarEntidadesFederativasOut consultarEntidadesFederativas()
        throws ServiceException
    ;

    /**
     * 
     * @param pConsultarMotivosRechazoValCalIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.PConsultarMotivosRechazoValCalOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "PConsultarMotivosRechazoValCalOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarMotivosRechazoValCal", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarMotivosRechazoValCal")
    @ResponseWrapper(localName = "consultarMotivosRechazoValCalResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarMotivosRechazoValCalResponse")
    public PConsultarMotivosRechazoValCalOut consultarMotivosRechazoValCal(
        @WebParam(name = "PConsultarMotivosRechazoValCalIn", targetNamespace = "")
        PConsultarMotivosRechazoValCalIn pConsultarMotivosRechazoValCalIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarSubcuentaPorIdIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentaPorIdOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarSubcuentaPorIdOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarSubcuentaPorId", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentaPorId")
    @ResponseWrapper(localName = "consultarSubcuentaPorIdResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarSubcuentaPorIdResponse")
    public ConsultarSubcuentaPorIdOut consultarSubcuentaPorId(
        @WebParam(name = "consultarSubcuentaPorIdIn", targetNamespace = "")
        ConsultarSubcuentaPorIdIn consultarSubcuentaPorIdIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarCatOrigenAfiliacionIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarCatOrigenAfiliacionOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarCatOrigenAfiliacionOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarCatOrigenAfiliacion", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarCatOrigenAfiliacion")
    @ResponseWrapper(localName = "consultarCatOrigenAfiliacionResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarCatOrigenAfiliacionResponse")
    public ConsultarCatOrigenAfiliacionOut consultarCatOrigenAfiliacion(
        @WebParam(name = "consultarCatOrigenAfiliacionIn", targetNamespace = "")
        ConsultarCatOrigenAfiliacionIn consultarCatOrigenAfiliacionIn)
        throws ServiceException
    ;

    /**
     * 
     * @param agregarCodigoPostalIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.AgregarCodigoPostalOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "agregarCodigoPostalOut", targetNamespace = "")
    @RequestWrapper(localName = "agregarCodigoPostal", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.AgregarCodigoPostal")
    @ResponseWrapper(localName = "agregarCodigoPostalResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.AgregarCodigoPostalResponse")
    public AgregarCodigoPostalOut agregarCodigoPostal(
        @WebParam(name = "agregarCodigoPostalIn", targetNamespace = "")
        AgregarCodigoPostalIn agregarCodigoPostalIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarCodigoPostalIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarCodigoPostalOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarCodigoPostalOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarCodigoPostal", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarCodigoPostal")
    @ResponseWrapper(localName = "consultarCodigoPostalResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarCodigoPostalResponse")
    public ConsultarCodigoPostalOut consultarCodigoPostal(
        @WebParam(name = "consultarCodigoPostalIn", targetNamespace = "")
        ConsultarCodigoPostalIn consultarCodigoPostalIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarPromotorIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarPromotorOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarPromotorOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarPromotor", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarPromotor")
    @ResponseWrapper(localName = "consultarPromotorResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarPromotorResponse")
    public ConsultarPromotorOut consultarPromotor(
        @WebParam(name = "consultarPromotorIn", targetNamespace = "")
        ConsultarPromotorIn consultarPromotorIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarComponentesCorreoIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarComponentesCorreoOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "ConsultarComponentesCorreoOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarComponentesCorreo", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarComponentesCorreo")
    @ResponseWrapper(localName = "consultarComponentesCorreoResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarComponentesCorreoResponse")
    public ConsultarComponentesCorreoOut consultarComponentesCorreo(
        @WebParam(name = "ConsultarComponentesCorreoIn", targetNamespace = "")
        ConsultarComponentesCorreoIn consultarComponentesCorreoIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarAsentaminetosPorCPIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarAsentaminetosPorCPOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "ConsultarAsentaminetosPorCPOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarAsentamientosPorCP", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarAsentamientosPorCP")
    @ResponseWrapper(localName = "consultarAsentamientosPorCPResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarAsentamientosPorCPResponse")
    public ConsultarAsentaminetosPorCPOut consultarAsentamientosPorCP(
        @WebParam(name = "ConsultarAsentaminetosPorCPIn", targetNamespace = "")
        ConsultarAsentaminetosPorCPIn consultarAsentaminetosPorCPIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarSucursalIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarSucursalOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "consultarSucursalOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarSucursales", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarSucursales")
    @ResponseWrapper(localName = "consultarSucursalesResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarSucursalesResponse")
    public ConsultarSucursalOut consultarSucursales(
        @WebParam(name = "ConsultarSucursalIn", targetNamespace = "")
        ConsultarSucursalIn consultarSucursalIn)
        throws ServiceException
    ;

    /**
     * 
     * @param consultarEmpleadosPorRolIn
     * @return
     *     returns mx.com.profuturo_gnp.comun.catalogo.ConsultarEmpleadosPorRolOut
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "ConsultarEmpleadosPorRolOut", targetNamespace = "")
    @RequestWrapper(localName = "consultarEmpleadosPorRol", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarEmpleadosPorRol")
    @ResponseWrapper(localName = "consultarEmpleadosPorRolResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", className = "mx.com.profuturo_gnp.comun.catalogo.ConsultarEmpleadosPorRolResponse")
    public ConsultarEmpleadosPorRolOut consultarEmpleadosPorRol(
        @WebParam(name = "ConsultarEmpleadosPorRolIn", targetNamespace = "")
        ConsultarEmpleadosPorRolIn consultarEmpleadosPorRolIn)
        throws ServiceException
    ;

}
