
package profuturo.mx.iib.apovol.filenet.filenetservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import mx.profuturo.nci.ws.webservice.indicadores.impl.IIndicadoresSoapWSService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FileNetService", targetNamespace = "http://mx.profuturo/iib/apovol/FileNet/FileNetService/v1", wsdlLocation = "http://172.16.60.69:7801/iib/apovol/FileNet/FileNetService/v1?wsdl")
public class FileNetService
    extends Service
{

    private final static URL FILENETSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(profuturo.mx.iib.apovol.filenet.filenetservice.v1.FileNetService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = profuturo.mx.iib.apovol.filenet.filenetservice.v1.FileNetService.class.getResource(".");
            url = //new URL(baseUrl, "http://172.16.60.69:7801/iib/apovol/FileNet/FileNetService/v1?wsdl");
            		FileNetService.class.getClassLoader().getResource("config/wsdls/filenet/FileNetService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.60.69:7801/iib/apovol/FileNet/FileNetService/v1?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FILENETSERVICE_WSDL_LOCATION = url;
    }

    public FileNetService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileNetService() {
        super(FILENETSERVICE_WSDL_LOCATION, new QName("http://mx.profuturo/iib/apovol/FileNet/FileNetService/v1", "FileNetService"));
    }

    /**
     * 
     * @return
     *     returns FileNetPortType
     */
    @WebEndpoint(name = "FileNetPortType")
    public FileNetPortType getFileNetPortType() {
        return super.getPort(new QName("http://mx.profuturo/iib/apovol/FileNet/FileNetService/v1", "FileNetPortType"), FileNetPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileNetPortType
     */
    @WebEndpoint(name = "FileNetPortType")
    public FileNetPortType getFileNetPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.profuturo/iib/apovol/FileNet/FileNetService/v1", "FileNetPortType"), FileNetPortType.class, features);
    }

}
