
package profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ActualizarEstatusCuentaReq;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ActualizarEstatusCuentaResp;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.CancelarCuentaCertificadaReq;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.CancelarCuentaCertificadaResp;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ConsultarCuentasCertificacionReq;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ConsultarCuentasCertificacionResp;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ConsultarCuentasCertificadasReq;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ConsultarCuentasCertificadasResp;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.GuardaCuentaACertificarReq;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.GuardaCuentaACertificarResp;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.InsertarSolCertReq;
import profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.InsertarSolCertResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CuentasCertificadasPortType", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ObjectFactory.class,
    profuturo.mx.iib.iibexception.iibexception.ObjectFactory.class,
    profuturo.mx.nci.modelo.ObjectFactory.class
})
public interface CuentasCertificadasPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ConsultarCuentasCertificadasResp
     * @throws FaultMsg
     */
    @WebMethod(action = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/consultarCuentasCertificadas")
    @WebResult(name = "consultarCuentasCertificadasResponse", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
    public ConsultarCuentasCertificadasResp consultarCuentasCertificadas(
        @WebParam(name = "consultarCuentasCertificadasRequest", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
        ConsultarCuentasCertificadasReq parameters)
        throws FaultMsg
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ConsultarCuentasCertificacionResp
     * @throws FaultMsg
     */
    @WebMethod(action = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/consultarCuentasCertificacion")
    @WebResult(name = "consultarCuentasCertificacionResponse", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
    public ConsultarCuentasCertificacionResp consultarCuentasCertificacion(
        @WebParam(name = "consultarCuentasCertificacionRequest", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
        ConsultarCuentasCertificacionReq parameters)
        throws FaultMsg
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.GuardaCuentaACertificarResp
     * @throws FaultMsg
     */
    @WebMethod(action = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/guardaCuentaACertificar")
    @WebResult(name = "guardaCuentaACertificarResponse", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
    public GuardaCuentaACertificarResp guardaCuentaACertificar(
        @WebParam(name = "guardaCuentaACertificarRequest", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
        GuardaCuentaACertificarReq parameters)
        throws FaultMsg
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.CancelarCuentaCertificadaResp
     * @throws FaultMsg
     */
    @WebMethod(action = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/cancelarCuentaCertificada")
    @WebResult(name = "cancelarCuentaCertificadaResponse", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
    public CancelarCuentaCertificadaResp cancelarCuentaCertificada(
        @WebParam(name = "cancelarCuentaCertificadaRequest", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
        CancelarCuentaCertificadaReq parameters)
        throws FaultMsg
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.InsertarSolCertResp
     * @throws FaultMsg
     */
    @WebMethod(action = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/insertarSolicitudCertificacion")
    @WebResult(name = "insertarSolicitudCertificacionResponse", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
    public InsertarSolCertResp insertarSolicitudCertificacion(
        @WebParam(name = "insertarSolicitudCertificacionRequest", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
        InsertarSolCertReq parameters)
        throws FaultMsg
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.certif.certificaciones.cuentascertificadasservice.v1.types.ActualizarEstatusCuentaResp
     * @throws FaultMsg
     */
    @WebMethod(action = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/actualizarEstatusCuenta")
    @WebResult(name = "actualizarEstatusCuentaResponse", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
    public ActualizarEstatusCuentaResp actualizarEstatusCuenta(
        @WebParam(name = "actualizarEstatusCuentaRequest", targetNamespace = "http://mx.profuturo/iib/certif/Certificaciones/CuentasCertificadasService/v1/types", partName = "parameters")
        ActualizarEstatusCuentaReq parameters)
        throws FaultMsg
    ;

}
