
package profuturo.mx.iib.nci.notificaciones.enviocorreoservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import profuturo.mx.iib.nci.notificaciones.enviocorreoservice.v1.types.EnviarCorreoRequest;
import profuturo.mx.iib.nci.notificaciones.enviocorreoservice.v1.types.EnviarCorreoResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EnvioCorreoPortType", targetNamespace = "http://mx.profuturo/iib/nci/Notificaciones/EnvioCorreoService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    profuturo.mx.iib.nci.notificaciones.enviocorreoservice.v1.types.ObjectFactory.class,
    profuturo.mx.iib.iibexception.iibexception.ObjectFactory.class,
    profuturo.mx.nci.modelo.ObjectFactory.class
})
public interface EnvioCorreoPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.notificaciones.enviocorreoservice.v1.types.EnviarCorreoResponse
     */
    @WebMethod(action = "urn:enviarCorreo")
    @WebResult(name = "enviarCorreoResponse", targetNamespace = "http://mx.profuturo/iib/nci/Notificaciones/EnvioCorreoService/v1/types", partName = "parameters")
    public EnviarCorreoResponse enviarCorreo(
        @WebParam(name = "enviarCorreoRequest", targetNamespace = "http://mx.profuturo/iib/nci/Notificaciones/EnvioCorreoService/v1/types", partName = "parameters")
        EnviarCorreoRequest parameters);

}
