
package mx.com.profuturo_gnp.comun.catalogo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CatalogoComunService", targetNamespace = "http://www.profuturo-gnp.com.mx/comun/Catalogo", wsdlLocation = "classpath:config/wsdls/usuario/CatalogoComunService.wsdl")
public class CatalogoComunService
    extends Service
{

    private final static URL CATALOGOCOMUNSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.com.profuturo_gnp.comun.catalogo.CatalogoComunService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.com.profuturo_gnp.comun.catalogo.CatalogoComunService.class.getResource(".");
            url = //new URL(baseUrl, "classpath:config/wsdls/usuario/CatalogoComunService.wsdl");
            CatalogoComunService.class.getClassLoader().getResource("config/wsdls/usuario/CatalogoComunService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/j-everis3.2/workspace.int/mit-ws-client/src/main/resources/wsdls/usuario/CatalogoComunService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CATALOGOCOMUNSERVICE_WSDL_LOCATION = url;
    }

    public CatalogoComunService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogoComunService() {
        super(CATALOGOCOMUNSERVICE_WSDL_LOCATION, new QName("http://www.profuturo-gnp.com.mx/comun/Catalogo", "CatalogoComunService"));
    }

    /**
     * 
     * @return
     *     returns CatalogoComun
     */
    @WebEndpoint(name = "CatalogoComunServicePort")
    public CatalogoComun getCatalogoComunServicePort() {
        return super.getPort(new QName("http://www.profuturo-gnp.com.mx/comun/Catalogo", "CatalogoComunServicePort"), CatalogoComun.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogoComun
     */
    @WebEndpoint(name = "CatalogoComunServicePort")
    public CatalogoComun getCatalogoComunServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.profuturo-gnp.com.mx/comun/Catalogo", "CatalogoComunServicePort"), CatalogoComun.class, features);
    }

}
