
package mx.com.profuturo_gnp.ws.sso.controlacceso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ControlAccesoSSOPortType", targetNamespace = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControlAccesoSSOPortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns mx.com.profuturo_gnp.ws.sso.controlacceso.AutenticacionResponse
     * @throws SSOFault
     */
    @WebMethod(action = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso/autenticarUsuarioSSO")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticarUsuarioSSO", targetNamespace = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", className = "mx.com.profuturo_gnp.ws.sso.controlacceso.AutenticarUsuarioSSO")
    @ResponseWrapper(localName = "autenticarUsuarioSSOResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", className = "mx.com.profuturo_gnp.ws.sso.controlacceso.AutenticarUsuarioSSOResponse")
    public AutenticacionResponse autenticarUsuarioSSO(
        @WebParam(name = "arg0", targetNamespace = "")
        AutenticacionRequest arg0)
        throws SSOFault
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.com.profuturo_gnp.ws.sso.controlacceso.AutorizacionResponse
     * @throws SSOFault
     */
    @WebMethod(action = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso/autorizarUsuarioSSO")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autorizarUsuarioSSO", targetNamespace = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", className = "mx.com.profuturo_gnp.ws.sso.controlacceso.AutorizarUsuarioSSO")
    @ResponseWrapper(localName = "autorizarUsuarioSSOResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", className = "mx.com.profuturo_gnp.ws.sso.controlacceso.AutorizarUsuarioSSOResponse")
    public AutorizacionResponse autorizarUsuarioSSO(
        @WebParam(name = "arg0", targetNamespace = "")
        AutorizacionRequest arg0)
        throws SSOFault
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.com.profuturo_gnp.ws.sso.controlacceso.ConfirmarAccesoResponse
     * @throws SSOFault
     */
    @WebMethod(action = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso/confirmarAccesoUsuarioSSO")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmarAccesoUsuarioSSO", targetNamespace = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", className = "mx.com.profuturo_gnp.ws.sso.controlacceso.ConfirmarAccesoUsuarioSSO")
    @ResponseWrapper(localName = "confirmarAccesoUsuarioSSOResponse", targetNamespace = "http://www.profuturo-gnp.com.mx/ws/sso/controlacceso", className = "mx.com.profuturo_gnp.ws.sso.controlacceso.ConfirmarAccesoUsuarioSSOResponse")
    public ConfirmarAccesoResponse confirmarAccesoUsuarioSSO(
        @WebParam(name = "arg0", targetNamespace = "")
        ConfirmarAccesoRequest arg0)
        throws SSOFault
    ;

}
