
package mx.profuturo.nci.ws.webservice.indicadores.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.profuturo.nci.ws.webservice.indicadores.ConsultaIndicadoresBeanRequest;
import mx.profuturo.nci.ws.webservice.indicadores.IIndicadoresSoapWSConsultaBasicaResponse;
import mx.profuturo.nci.ws.webservice.indicadores.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IIndicadoresSoapWS", targetNamespace = "http://indicadores.webservice.ws.nci.profuturo.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IIndicadoresSoapWS {


    /**
     * 
     * @param req
     * @return
     *     returns mx.profuturo.nci.ws.webservice.indicadores.IIndicadoresSoapWSConsultaBasicaResponse
     */
    @WebMethod
    @WebResult(name = "ConsultaBasicaResponse", targetNamespace = "")
    @RequestWrapper(localName = "consultaBasica", targetNamespace = "http://indicadores.webservice.ws.nci.profuturo.mx/", className = "mx.profuturo.nci.ws.webservice.indicadores.ConsultaBasica")
    @ResponseWrapper(localName = "consultaBasicaResponse", targetNamespace = "http://indicadores.webservice.ws.nci.profuturo.mx/", className = "mx.profuturo.nci.ws.webservice.indicadores.ConsultaBasicaResponse")
    public IIndicadoresSoapWSConsultaBasicaResponse consultaBasica(
        @WebParam(name = "req", targetNamespace = "")
        ConsultaIndicadoresBeanRequest req);

}
