
package profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ActualizarFolioReq;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ActualizarFolioResp;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ConsultarFolioARelacionarReq;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ConsultarFolioARelacionarResp;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ConsultarFoliosRelacionadosReq;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ConsultarFoliosRelacionadosResp;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.GenerarFolioReq;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.GenerarFolioResp;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.GuardarFolioReq;
import profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.GuardarFolioResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FolioPortType", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    profuturo.mx.nci.modelo.ObjectFactory.class,
    profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ObjectFactory.class,
    profuturo.mx.iib.iibexception.iibexception.ObjectFactory.class
})
public interface FolioPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.GenerarFolioResp
     */
    @WebMethod(action = "urn:generarFolio")
    @WebResult(name = "generarFolioResponse", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
    public GenerarFolioResp generarFolio(
        @WebParam(name = "generarFolioRequest", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
        GenerarFolioReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.GuardarFolioResp
     */
    @WebMethod(action = "urn:guardarFolio")
    @WebResult(name = "guardarFolioResponse", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
    public GuardarFolioResp guardarFolio(
        @WebParam(name = "guardarFolioRequest", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
        GuardarFolioReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ActualizarFolioResp
     */
    @WebMethod(action = "urn:actualizarFolio")
    @WebResult(name = "actualizarFolioResponse", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
    public ActualizarFolioResp actualizarFolio(
        @WebParam(name = "actualizarFolioRequest", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
        ActualizarFolioReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ConsultarFolioARelacionarResp
     */
    @WebMethod(action = "urn:consultarFolioARelacionar")
    @WebResult(name = "consultarFolioARelacionarResponse", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
    public ConsultarFolioARelacionarResp consultarFolioARelacionar(
        @WebParam(name = "consultarFolioARelacionarRequest", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
        ConsultarFolioARelacionarReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.types.ConsultarFoliosRelacionadosResp
     */
    @WebMethod(action = "urn:consultarFoliosRelacionados")
    @WebResult(name = "consultarFoliosRelacionadosResponse", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameter")
    public ConsultarFoliosRelacionadosResp consultarFoliosRelacionados(
        @WebParam(name = "consultarFoliosRelacionadosRequest", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1/types", partName = "parameters")
        ConsultarFoliosRelacionadosReq parameters);

}
