
package profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConciliacionService", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1", wsdlLocation = "file:/opt/IDE/workspace.fase2/mit-ws-client/src/main/resources/config/wsdls/conciliacion/ConciliacionService.wsdl")
public class ConciliacionService
    extends Service
{

    private final static URL CONCILIACIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.ConciliacionService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.ConciliacionService.class.getResource(".");
            url = //new URL(baseUrl, "file:/opt/IDE/workspace.fase2/mit-ws-client/src/main/resources/config/wsdls/conciliacion/ConciliacionService.wsdl");
            		ConciliacionService.class.getClassLoader().getResource("config/wsdls/conciliacion/ConciliacionService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/opt/IDE/workspace.fase2/mit-ws-client/src/main/resources/config/wsdls/conciliacion/ConciliacionService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONCILIACIONSERVICE_WSDL_LOCATION = url;
    }

    public ConciliacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConciliacionService() {
        super(CONCILIACIONSERVICE_WSDL_LOCATION, new QName("http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1", "ConciliacionService"));
    }

    /**
     * 
     * @return
     *     returns ConciliacionPortType
     */
    @WebEndpoint(name = "ConciliacionPort")
    public ConciliacionPortType getConciliacionPort() {
        return super.getPort(new QName("http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1", "ConciliacionPort"), ConciliacionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConciliacionPortType
     */
    @WebEndpoint(name = "ConciliacionPort")
    public ConciliacionPortType getConciliacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1", "ConciliacionPort"), ConciliacionPortType.class, features);
    }

}
