package mx.profuturo.nci.business.vo;

import java.io.Serializable;


public class SubprocesoVO implements Serializable {

  /**
   * Generated by Eclipse
   */
  private static final long serialVersionUID = -3712454875542652034L;

  private Short idSubproceso;
    private String descSubproceso;

    public SubprocesoVO(){}




    public SubprocesoVO(final Short idSubproceso, final String descSubproceso) {

		this.idSubproceso = idSubproceso;
		this.descSubproceso = descSubproceso;
	}




	public SubprocesoVO(final Short idSubproceso) {
		this.idSubproceso = idSubproceso;
	}

	public Short getIdSubproceso() {
		return idSubproceso;
	}

	public void setIdSubproceso(final Short idSubproceso) {
		this.idSubproceso = idSubproceso;
	}

	public String getDescSubproceso() {
		return descSubproceso;
	}

	public void setDescSubproceso(final String descSubproceso) {
		this.descSubproceso = descSubproceso;
	}


	@Override
	public String toString() {
		return "SubprocesoVO "+ "["+ "idSubproceso = " + idSubproceso+ ", descSubproceso = " + descSubproceso  + "]";
	}




}