
package mx.profuturo.nci.ws.webservice.catalogo.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ICatalogoSoapWSService", targetNamespace = "http://impl.catalogo.webservice.ws.nci.profuturo.mx/", wsdlLocation = "http://172.16.60.67:9085/mit-ws/services/ICatalogoSoapWSService?wsdl")
public class ICatalogoSoapWSService
    extends Service
{

    private final static URL ICATALOGOSOAPWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.profuturo.nci.ws.webservice.catalogo.impl.ICatalogoSoapWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.profuturo.nci.ws.webservice.catalogo.impl.ICatalogoSoapWSService.class.getResource(".");
            url = //new URL(baseUrl, "http://172.16.60.67:9085/mit-ws/services/ICatalogoSoapWSService?wsdl");
            		ICatalogoSoapWSService	.class.getClassLoader().getResource("config/wsdls/catalogo/ICatalogoSoapWSService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.16.60.67:9085/mit-ws/services/ICatalogoSoapWSService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ICATALOGOSOAPWSSERVICE_WSDL_LOCATION = url;
    }

    public ICatalogoSoapWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ICatalogoSoapWSService() {
        super(ICATALOGOSOAPWSSERVICE_WSDL_LOCATION, new QName("http://impl.catalogo.webservice.ws.nci.profuturo.mx/", "ICatalogoSoapWSService"));
    }

    /**
     * 
     * @return
     *     returns ICatalogoSoapWS
     */
    @WebEndpoint(name = "ICatalogoSoapWSPort")
    public ICatalogoSoapWS getICatalogoSoapWSPort() {
        return super.getPort(new QName("http://impl.catalogo.webservice.ws.nci.profuturo.mx/", "ICatalogoSoapWSPort"), ICatalogoSoapWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICatalogoSoapWS
     */
    @WebEndpoint(name = "ICatalogoSoapWSPort")
    public ICatalogoSoapWS getICatalogoSoapWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.catalogo.webservice.ws.nci.profuturo.mx/", "ICatalogoSoapWSPort"), ICatalogoSoapWS.class, features);
    }

}
