
package mx.secure.ldap.operacionesldap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OperacionesLdapServices", targetNamespace = "http://www.secure.mx/ldap/OperacionesLdap")
@XmlSeeAlso({
    mx.com.secure_gnp.web.exception.ObjectFactory.class,
    mx.secure.ldap.operacionesldap.ObjectFactory.class
})
public interface OperacionesLdapServices {


    /**
     * 
     * @param consultaGruposPorUidIn
     * @return
     *     returns mx.secure.ldap.operacionesldap.ConsultaGruposPorUidOut
     * @throws ServiceException
     */
    @WebMethod(operationName = "ConsultaGruposPorUid")
    @WebResult(name = "ConsultaGruposPorUidOut", targetNamespace = "")
    @RequestWrapper(localName = "ConsultaGruposPorUid", targetNamespace = "http://www.secure.mx/ldap/OperacionesLdap", className = "mx.secure.ldap.operacionesldap.ConsultaGruposPorUid")
    @ResponseWrapper(localName = "ConsultaGruposPorUidResponse", targetNamespace = "http://www.secure.mx/ldap/OperacionesLdap", className = "mx.secure.ldap.operacionesldap.ConsultaGruposPorUidResponse")
    public ConsultaGruposPorUidOut consultaGruposPorUid(
        @WebParam(name = "ConsultaGruposPorUidIn", targetNamespace = "")
        ConsultaGruposPorUidIn consultaGruposPorUidIn)
        throws ServiceException
    ;

}
