
package profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClienteBasicoReq;
import profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClienteBasicoResp;
import profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClienteReq;
import profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClienteResp;
import profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClientesNoIdentificadosReq;
import profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClientesNoIdentificadosResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientePortType", targetNamespace = "http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    profuturo.mx.iib.iibexception.iibexception.ObjectFactory.class,
    profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ObjectFactory.class,
    profuturo.mx.nci.modelo.ObjectFactory.class
})
public interface ClientePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClientesNoIdentificadosResp
     * @throws FaultMsg
     */
    @WebMethod(action = "urn:consultarClientesNoIdentificados")
    @WebResult(name = "consultarClientesNoIdentificadosResponse", targetNamespace = "http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1/types", partName = "parameters")
    public ConsultarClientesNoIdentificadosResp consultarClientesNoIdentificados(
        @WebParam(name = "consultarClientesNoIdentificadosRequest", targetNamespace = "http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1/types", partName = "parameters")
        ConsultarClientesNoIdentificadosReq parameters)
        throws FaultMsg
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClienteBasicoResp
     * @throws FaultMsg
     */
    @WebMethod(action = "urn:consultarClienteBasico")
    @WebResult(name = "consultarClienteBasicoResponse", targetNamespace = "http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1/types", partName = "parameters")
    public ConsultarClienteBasicoResp consultarClienteBasico(
        @WebParam(name = "consultarClienteBasicoRequest", targetNamespace = "http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1/types", partName = "parameters")
        ConsultarClienteBasicoReq parameters)
        throws FaultMsg
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.identificacioncliente.clienteservice.v1.types.ConsultarClienteResp
     * @throws FaultMsg
     */
    @WebMethod(action = "urn:consultarCliente")
    @WebResult(name = "consultarClienteResponse", targetNamespace = "http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1/types", partName = "parameters")
    public ConsultarClienteResp consultarCliente(
        @WebParam(name = "consultarClienteRequest", targetNamespace = "http://mx.profuturo/iib/nci/IdentificacionCliente/ClienteService/v1/types", partName = "parameters")
        ConsultarClienteReq parameters)
        throws FaultMsg
    ;

}
