
package profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FolioService", targetNamespace = "http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1", wsdlLocation = "file:/C:/Users/eromerod/Documents/Profuturo/NCI_MONITOR/mit-ws-client/src/main/resources/wsdls/folio/FolioService.wsdl")
public class FolioService
    extends Service
{

    private final static URL FOLIOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.FolioService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = profuturo.mx.iib.nci.bitacoraprocesos.folioservice.v1.FolioService.class.getResource(".");
            url = //new URL(baseUrl, "file:/C:/Users/eromerod/Documents/Profuturo/NCI_MONITOR/mit-ws-client/src/main/resources/wsdls/folio/FolioService.wsdl");
            FolioService.class.getClassLoader().getResource("config/wsdls/folio/FolioService.wsdl");
            
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/eromerod/Documents/Profuturo/NCI_MONITOR/mit-ws-client/src/main/resources/wsdls/folio/FolioService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FOLIOSERVICE_WSDL_LOCATION = url;
    }

    public FolioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FolioService() {
        super(FOLIOSERVICE_WSDL_LOCATION, new QName("http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1", "FolioService"));
    }

    /**
     * 
     * @return
     *     returns FolioPortType
     */
    @WebEndpoint(name = "FolioPort")
    public FolioPortType getFolioPort() {
        return super.getPort(new QName("http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1", "FolioPort"), FolioPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FolioPortType
     */
    @WebEndpoint(name = "FolioPort")
    public FolioPortType getFolioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.profuturo/iib/nci/BitacoraProcesos/FolioService/v1", "FolioPort"), FolioPortType.class, features);
    }

}
