
package profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ActualizarConciliacionReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ActualizarConciliacionResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.AsociarMovimientosConArchivoReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.AsociarMovimientosConArchivoResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConciliarReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConciliarResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarAportacionesConciliadasReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarAportacionesConciliadasResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosBancariosReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosBancariosResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosNoConciliadosReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosNoConciliadosResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosPorConciliarReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosPorConciliarResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarConciliacionReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarConciliacionResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarCuantosRegistrosReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarCuantosRegistrosResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarFoliosPorConciliarReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarFoliosPorConciliarResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarMovimientosNoConciliadosReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarMovimientosNoConciliadosResp;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.LiberarMovimientosReq;
import profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.LiberarMovimientosResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ConciliacionPortType", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    profuturo.mx.iib.iibexception.iibexception.ObjectFactory.class,
    profuturo.mx.nci.modelo.ObjectFactory.class,
    profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ObjectFactory.class
})
public interface ConciliacionPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosPorConciliarResp
     */
    @WebMethod(action = "urn:consultarArchivosPorConciliar")
    @WebResult(name = "consultarArchivosPorConciliarResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConsultarArchivosPorConciliarResp consultarArchivosPorConciliar(
        @WebParam(name = "consultarArchivosPorConciliarRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConsultarArchivosPorConciliarReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosBancariosResp
     */
    @WebMethod(action = "urn:consultarArchivosBancarios")
    @WebResult(name = "consultarArchivosBancariosResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConsultarArchivosBancariosResp consultarArchivosBancarios(
        @WebParam(name = "consultarArchivosBancariosRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConsultarArchivosBancariosReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarAportacionesConciliadasResp
     */
    @WebMethod(action = "urn:consultarAportacionesConciliadas")
    @WebResult(name = "consultarAportacionesConciliadasResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConsultarAportacionesConciliadasResp consultarAportacionesConciliadas(
        @WebParam(name = "consultarAportacionesConciliadasRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConsultarAportacionesConciliadasReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConciliarResp
     */
    @WebMethod(action = "urn:conciliar")
    @WebResult(name = "conciliarResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConciliarResp conciliar(
        @WebParam(name = "conciliarRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConciliarReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarArchivosNoConciliadosResp
     */
    @WebMethod(action = "urn:consultarArchivosNoConciliados")
    @WebResult(name = "consultarArchivosNoConciliadosResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConsultarArchivosNoConciliadosResp consultarArchivosNoConciliados(
        @WebParam(name = "consultarArchivosNoConciliadosRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConsultarArchivosNoConciliadosReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarMovimientosNoConciliadosResp
     */
    @WebMethod(action = "urn:consultarMovimientosNoConciliados")
    @WebResult(name = "consultarMovimientosNoConciliadosResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConsultarMovimientosNoConciliadosResp consultarMovimientosNoConciliados(
        @WebParam(name = "consultarMovimientosNoConciliadosRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConsultarMovimientosNoConciliadosReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.AsociarMovimientosConArchivoResp
     */
    @WebMethod(action = "urn:asociarMovimientosConArchivo")
    @WebResult(name = "asociarMovimientosConArchivoResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public AsociarMovimientosConArchivoResp asociarMovimientosConArchivo(
        @WebParam(name = "asociarMovimientosConArchivoRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        AsociarMovimientosConArchivoReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarConciliacionResp
     */
    @WebMethod(action = "urn:consultarConciliacion")
    @WebResult(name = "consultarConciliacionResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConsultarConciliacionResp consultarConciliacion(
        @WebParam(name = "consultarConciliacionRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConsultarConciliacionReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ActualizarConciliacionResp
     */
    @WebMethod(action = "urn:actualizarConciliacion")
    @WebResult(name = "actualizarConciliacionResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ActualizarConciliacionResp actualizarConciliacion(
        @WebParam(name = "actualizarConciliacionRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ActualizarConciliacionReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarFoliosPorConciliarResp
     */
    @WebMethod(action = "urn:consultarFoliosPorConciliar")
    @WebResult(name = "consultarFoliosPorConciliarResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConsultarFoliosPorConciliarResp consultarFoliosPorConciliar(
        @WebParam(name = "consultarFoliosPorConciliarRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConsultarFoliosPorConciliarReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.ConsultarCuantosRegistrosResp
     */
    @WebMethod(action = "urn:consultarCuantosRegistros")
    @WebResult(name = "consultarCuantosRegistrosResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public ConsultarCuantosRegistrosResp consultarCuantosRegistros(
        @WebParam(name = "consultarCuantosRegistrosRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        ConsultarCuantosRegistrosReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.apovol.conciliacion.conciliacionservice.v1.types.LiberarMovimientosResp
     */
    @WebMethod(action = "urn:liberarMovimientos")
    @WebResult(name = "liberarMovimientosResponse", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
    public LiberarMovimientosResp liberarMovimientos(
        @WebParam(name = "liberarMovimientosRequest", targetNamespace = "http://mx.profuturo/iib/apovol/Conciliacion/ConciliacionService/v1/types", partName = "parameters")
        LiberarMovimientosReq parameters);

}
