
package profuturo.mx.iib.nci.notificaciones.enviocorreoservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import mx.profuturo.nci.business.util.NameSpaceBindingProvider;
import mx.profuturo.nci.business.util.WebSphereNamespace;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EnvioCorreoService", targetNamespace = "http://mx.profuturo/iib/nci/Notificaciones/EnvioCorreoService/v1", wsdlLocation = "http://iibnci.profuturo.mx:7800/iib/Notificaciones/EnvioCorreoService/v1?wsdl")
public class EnvioCorreoService
    extends Service
{

    private final static URL ENVIOCORREOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(profuturo.mx.iib.nci.notificaciones.enviocorreoservice.v1.EnvioCorreoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = profuturo.mx.iib.nci.notificaciones.enviocorreoservice.v1.EnvioCorreoService.class.getResource(".");
            url = new URL(baseUrl, NameSpaceBindingProvider.getValue(WebSphereNamespace.ws_endpoint_client_notificaciones)+"?wsdl");
            		EnvioCorreoService.class.getClassLoader().getResource("config/wsdls/envioCcorreo/EnvioCorreoService.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'config/wsdls/envioCcorreo/EnvioCorreoService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ENVIOCORREOSERVICE_WSDL_LOCATION = url;
    }

    public EnvioCorreoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnvioCorreoService() {
        super(ENVIOCORREOSERVICE_WSDL_LOCATION, new QName("http://mx.profuturo/iib/nci/Notificaciones/EnvioCorreoService/v1", "EnvioCorreoService"));
    }

    /**
     * 
     * @return
     *     returns EnvioCorreoPortType
     */
    @WebEndpoint(name = "EnvioCorreoPort")
    public EnvioCorreoPortType getEnvioCorreoPort() {
        return super.getPort(new QName("http://mx.profuturo/iib/nci/Notificaciones/EnvioCorreoService/v1", "EnvioCorreoPort"), EnvioCorreoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnvioCorreoPortType
     */
    @WebEndpoint(name = "EnvioCorreoPort")
    public EnvioCorreoPortType getEnvioCorreoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mx.profuturo/iib/nci/Notificaciones/EnvioCorreoService/v1", "EnvioCorreoPort"), EnvioCorreoPortType.class, features);
    }

}
