
package profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.types.ConsultarConvivenciaReq;
import profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.types.ConsultarConvivenciaResp;
import profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.types.ConsultarCuentasNoConvivenReq;
import profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.types.ConsultarCuentasNoConvivenResp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MatrizConvivenciaPortType", targetNamespace = "http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.types.ObjectFactory.class,
    profuturo.mx.iib.iibexception.iibexception.ObjectFactory.class,
    profuturo.mx.nci.modelo.ObjectFactory.class
})
public interface MatrizConvivenciaPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.types.ConsultarCuentasNoConvivenResp
     */
    @WebMethod(action = "urn:consultarCuentasNoConviven")
    @WebResult(name = "consultarCuentasNoConvivenResponse", targetNamespace = "http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1/types", partName = "parameters")
    public ConsultarCuentasNoConvivenResp consultarCuentasNoConviven(
        @WebParam(name = "consultarCuentasNoConvivenRequest", targetNamespace = "http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1/types", partName = "parameters")
        ConsultarCuentasNoConvivenReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns profuturo.mx.iib.nci.matrizconvivencia.matrizconvivenciaservice.v1.types.ConsultarConvivenciaResp
     */
    @WebMethod(action = "urn:consultarConvivencia")
    @WebResult(name = "consultarConvivenciaResponse", targetNamespace = "http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1/types", partName = "parameters")
    public ConsultarConvivenciaResp consultarConvivencia(
        @WebParam(name = "consultarConvivenciaRequest", targetNamespace = "http://mx.profuturo/iib/nci/MatrizConvivencia/MatrizConvivenciaService/v1/types", partName = "parameters")
        ConsultarConvivenciaReq parameters);

}
