
package mx.com.profuturo_gnp.comun.catalogo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "FaultBeanServiceInfo", targetNamespace = "http://www.profuturo-gnp.com.mx/web/exception")
public class ServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultBeanServiceInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServiceException(String message, FaultBeanServiceInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServiceException(String message, FaultBeanServiceInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mx.com.profuturo_gnp.comun.catalogo.FaultBeanServiceInfo
     */
    public FaultBeanServiceInfo getFaultInfo() {
        return faultInfo;
    }

}
